/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Genre;
import domain.Movie;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jodus
 */
public class GenresPanel extends javax.swing.JPanel implements GUIPanel {

    private final GenresPanelViewModel viewModel;

    /**
     * Creates new form GenresPanel
     */
    public GenresPanel() {
        initComponents();
        
        jGenreBox.setModel(new DefaultComboBoxModel<>());
        jMovieList.setModel(new DefaultListModel<>());
        
        this.viewModel = new GenresPanelViewModel();
        update();
        
        Client.getInstance().accept(this);
    }
    
    @Override
    public void update() {
        viewModel.fetchGenreList();
        viewModel.fetchMovieList();
        updateGenreBox();
        updateMoviesList();
    }
    
    private void updateGenreBox() {
        DefaultComboBoxModel genreList = (DefaultComboBoxModel) jGenreBox.getModel();
        genreList.removeAllElements();
        for (Genre genre: viewModel.getGenreList()) {
            genreList.addElement(genre.name);
        }
        jGenreBox.setSelectedIndex(viewModel.getSelectedIndex());
    }
    
    private void updateMoviesList() {
        DefaultListModel moviesList = (DefaultListModel) jMovieList.getModel();
        moviesList.removeAllElements();
        for (Movie movie: viewModel.getMovieList()) {
            moviesList.addElement(movie.title);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jGenreBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMovieList = new javax.swing.JList<>();
        jAddBtn = new javax.swing.JButton();
        jDeleteBtn = new javax.swing.JButton();

        jLabel2.setText("Genre:");

        jGenreBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jGenreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenreBoxActionPerformed(evt);
            }
        });

        jMovieList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jMovieList);

        jAddBtn.setText("Add");
        jAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBtnActionPerformed(evt);
            }
        });

        jDeleteBtn.setText("Delete");
        jDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jGenreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jAddBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDeleteBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jGenreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jAddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDeleteBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBtnActionPerformed
        String name = JOptionPane.showInputDialog(this, "Create a new genre");
        if (name != null) {
            viewModel.handleGenreCreate(name);
        }
    }//GEN-LAST:event_jAddBtnActionPerformed

    private void jGenreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenreBoxActionPerformed
        if (jGenreBox.getSelectedIndex() > -1) {
            int genreIndex = jGenreBox.getSelectedIndex();
            Genre g = viewModel.getGenreList().get(genreIndex);
            viewModel.handleSelectedGenreChange(g);
            update();
        }
    }//GEN-LAST:event_jGenreBoxActionPerformed

    private void jDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBtnActionPerformed
        int genreIndex = jGenreBox.getSelectedIndex();
        if (genreIndex > -1) {
            Genre g = viewModel.getGenreList().get(genreIndex);
            int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the grenre: " + g.name);
            if (result == JOptionPane.OK_OPTION) {
                viewModel.handleGenreDelete(g);
            }
        }
    }//GEN-LAST:event_jDeleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddBtn;
    private javax.swing.JButton jDeleteBtn;
    private javax.swing.JComboBox<String> jGenreBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jMovieList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
